version: '3'

# volumes:
  # postgres_data_dev: {}
  # postgres_backup_dev: {}

services:
  postgres:
    build: ./compose/postgres
    # volumes:
    #   - postgres_data_dev:/var/lib/postgresql/data
    #   - postgres_backup_dev:/backups
    environment:
      - POSTGRES_USER=fintify
      - POSTGRES_DB_NAME=fintifydb
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
      args:
        PIP_ARGS: ${PIP_ARGS}
    command: /start-dev.sh
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=fintify
      - USE_DOCKER=yes
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - postgres
