version: '3'

volumes:
  postgres_data_test: {}
  postgres_backup_test: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
      - postgres_backup_test:/backups
    environment:
      - POSTGRES_USER=finchest

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-test
      args:
        PIP_ARGS: ${PIP_ARGS}
    command: /start-test.sh
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=finchest
      - USE_DOCKER=yes
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - PYTEST_WATCH=${PYTEST_WATCH}
    volumes:
      - /app:/app
    links:
      - postgres
